package com.netnumeri.shared.finance.ta;

public enum Pattern {
    NONE, // Abandoned Baby Candlestick example image from StockCharts.com A rare reversal pattern characterized by a gap followed by a Doji, which is then followed by another gap in the opposite direction. The shadows on the Doji must completely gap below or above the shadows of the first and third day.
    Abandoned_Baby_Bullish,
    Abandoned_Baby_Bearish,
    // Abandoned Baby Candlestick  A rare reversal pattern characterized by a gap followed by a Doji, which is then followed by another gap in the opposite direction. The shadows on the Doji must completely gap below or above the shadows of the first and third day.
    Dark_Cloud_Cover, // Dark Cloud Cover Candlestick  A bearish reversal pattern that continues the uptrend with a long white body. The next day opens at a new high then closes below the midpoint of the body of the first day.
    Doji, // Doji Candlestick  Doji form when a security's open and close are virtually equal. The length of the upper and lower shadows can vary, and the resulting candlestick looks like, either, a cross, inverted cross, or plus sign. Doji convey a sense of indecision or tug-of-war between buyers and sellers. Prices move above and below the opening level during the session, but close at or near the opening level.
    Downside_Tasuki_Gap, // Downside Tasuki Gap Candlestick  A continuation pattern with a long, black body followed by another black body that has gapped below the first one. The third day is white and opens within the body of the second day, then closes in the gap between the first two days, but does not close the gap.
    Dragonfly_Doji_Bullish, // Dragonfly Doji Candlestick  A Doji where the open and close price are at the high of the day. Like other Doji days, this one normally appears at market turning points.
    Dragonfly_Doji_Bearish, // Dragonfly Doji Candlestick  A Doji where the open and close price are at the high of the day. Like other Doji days, this one normally appears at market turning points.
    Engulfing_Pattern_Bullish, // Engulfing Pattern Candlestick  A reversal pattern that can be bearish or bullish, depending upon whether it appears at the end of an uptrend (bearish engulfing pattern) or a downtrend (bullish engulfing pattern). The first day is characterized by a small body, followed by a day whose body completely engulfs the previous day's body.
    Engulfing_Pattern_Bearish, // Engulfing Pattern Candlestick  A reversal pattern that can be bearish or bullish, depending upon whether it appears at the end of an uptrend (bearish engulfing pattern) or a downtrend (bullish engulfing pattern). The first day is characterized by a small body, followed by a day whose body completely engulfs the previous day's body.
    Evening_Doji_Star, // Evening Doji Star Candlestick  A three day bearish reversal pattern similar to the Evening Star. The uptrend continues with a large white body. The next day opens higher, trades in a small range, then closes at its open (Doji). The next day closes below the midpoint of the body of the first day.
    Evening_Star, // Evening Star Candlestick  A bearish reversal pattern that continues an uptrend with a long white body day followed by a gapped up small body day, then a down close with the close below the midpoint of the first day.
    Falling_Three_Methods, // Falling Three Methods Candlestick  A bearish continuation pattern. A long black body is followed by three small body days, each fully contained within the range of the high and low of the first day. The fifth day closes at a new low.
    Gravestone_Doji, // Gravestone Doji Candlestick  A doji line that develops when the Doji is at, or very near, the low of the day.
    Hammer, // Hammer Candlestick  Hammer candlesticks form when a security moves significantly lower after the open, but rallies to close well above the intraday low. The resulting candlestick looks like a square lollipop with a long stick. If this candlestick forms during an advance, then it is called a Hanging Man.
    Hanging_Man, // Hanging Man Candlestick  Hanging Man candlesticks form when a security moves significantly lower after the open, but rallies to close well above the intraday low. The resulting candlestick looks like a square lollipop with a long stick. If this candlestick forms during a decline, then it is called a Hammer.
    Harami, // Harami Candlestick  A two day pattern that has a small body day completely contained within the range of the previous body, and is the opposite color.
    Harami_Cross, // Harami Cross Candlestick  A two day pattern similar to the Harami. The difference is that the last day is a Doji.
    Inverted_Hammer, // Inverted Hammer Candlestick  A one day bullish reversal pattern. In a downtrend, the open is lower, then it trades higher, but closes near its open, therefore looking like an inverted lollipop.
    Long_Day, // Long TDay Candlestick  A long day represents a large price move from open to close, where the length of the candle body is long.
    Long_Legged_Doji, // Long-legged Doji Candlestick  This candlestick has long upper and lower shadows with the Doji in the middle of the day's trading range, clearly reflecting the indecision of traders.
    Long_Shadows, // Long Shadows Long Shadows Candlestick  Candlesticks with a long upper shadow and short lower shadow indicate that buyers dominated during the session and bid prices higher. Conversely, candlesticks with long lower shadows and short upper shadows indicate that sellers dominated during the session and drove prices lower.
    Marubozo, // Marubozu Candlestick  A candlestick with no shadow extending from the body at either the open, the close or at both. The name means close-cropped or close-cut in Japanese, though other interpretations refer to it as Bald or Shaven Head.
    Morning_Doji_Star, // Morning Doji Star Candlestick  A three day bullish reversal pattern that is very similar to the Morning Star. The first day is in a downtrend with a long black body. The next day opens lower with a Doji that has a small trading range. The last day closes above the midpoint of the first day.
    Morning_Star, // Morning Star Candlestick  A three day bullish reversal pattern consisting of three candlesticks - a long-bodied black candle extending the current downtrend, a short middle candle that gapped down on the open, and a long-bodied white candle that gapped up on the open and closed above the midpoint of the body of the first day.
    Piercing_Line, // Piercing Line Candlestick  A bullish two day reversal pattern. The first day, in a downtrend, is a long black day. The next day opens at a new low, then closes above the midpoint of the body of the first day.
    Rising_Three_Methods, // Rising Three Methods Candlestick  A bullish continuation pattern in which a long white body is followed by three small body days, each fully contained within the range of the high and low of the first day. The fifth day closes at a new high.
    Shooting_Star, // Shooting Star Candlestick  A single day pattern that can appear in an uptrend. It opens higher, trades much higher, then closes near its open. It looks just like the Inverted Hammer except that it is bearish.
    Short_Day, // Short TDay Candlestick  A short day represents a small price move from open to close, where the length of the candle body is short.
    Spinning_Top, // Spinning Tops Candlestick  Candlestick lines that have small bodies with upper and lower shadows that exceed the length of the body. Spinning tops signal indecision.
    Stars, // Stars Candlestick  A candlestick that gaps away from the previous candlestick is said to be in star position. Depending on the previous candlestick, the star position candlestick gaps up or down and appears isolated from previous price action.
    Stick_Sandwich, // Stick Sandwich Candlestick  A bullish reversal pattern with two black bodies surrounding a white body. The closing prices of the two black bodies must be equal. A support prices is apparent and the opportunity for prices to reverse is quite good.
    Three_Black_Crows, // Three Black Crows Candlestick  A bearish reversal pattern consisting of three consecutive long black bodies where each day closes at or near its low and opens within the body of the previous day.
    Three_White_Soldiers, // Three White Soldiers Candlestick  A bullish reversal pattern consisting of three consecutive long white bodies. Each should open within the previous body and the close should be near the high of the day.
    Upside_Gap_Two_Crows, // Upside Gap Two Crows Candlestick  A three day bearish pattern that only happens in an uptrend. The first day is a long white body followed by a gapped open with the small black body remaining gapped above the first day. The third day is also a black day whose body is larger than the second day and engulfs it. The close of the last day is still above the first long white day.
    Upside_Tasuki_Gap // Upside Tasuki Gap Candlestick  A continuation pattern with a long white body followed by another white body that has gapped above the first one. The third day is black and opens within the body of the second day, then closes in the gap between the first two days, but does not close the gap.

}