package com.netnumeri.shared.enumer;


public enum CountryEnum {
    AD("Andorra", CurrencyEnum.EUR),
    AF("Afghanistan", CurrencyEnum.AFN),
    AX("Åland Islands", CurrencyEnum.USD),
    AL("Albania", CurrencyEnum.ALL),
    DZ("Algeria", CurrencyEnum.DZD),
    AS("American Samoa", CurrencyEnum.USD),
    AO("Angola", CurrencyEnum.AOA),
    AI("Anguilla", CurrencyEnum.XCD),
    AQ("Antarctica", CurrencyEnum.NOK),
    AG("Antigua and Barbuda", CurrencyEnum.XCD),
    AR("Argentina", CurrencyEnum.ARS),
    AM("Armenia", CurrencyEnum.AMD),
    AW("Aruba", CurrencyEnum.AWG),
    AU("Australia", CurrencyEnum.AUD),
    AT("Austria", CurrencyEnum.EUR),
    AZ("Azerbaijan", CurrencyEnum.AZN),
    BS("Bahamas", CurrencyEnum.BSD),
    BH("Bahrain", CurrencyEnum.BHD),
    BD("Bangladesh", CurrencyEnum.BDT),
    BB("Barbados", CurrencyEnum.BBD),
    BY("Belarus", CurrencyEnum.BYR),
    BE("Belgium", CurrencyEnum.EUR),
    BZ("Belize", CurrencyEnum.BZD),
    BJ("Benin", CurrencyEnum.XAF),
    BM("Bermuda", CurrencyEnum.BMD),
    BT("Bhutan", CurrencyEnum.BTN),
    BO("Bolivia", CurrencyEnum.BOB),
    BA("Bosnia and Herzegovina", CurrencyEnum.BAM),
    BW("Botswana", CurrencyEnum.BWP),
    BV("Bouvet Island", CurrencyEnum.NOK),
    BR("Brazil", CurrencyEnum.BRL),
    IO("British Indian Ocean Territory", CurrencyEnum.GBP),
    VG("British Virgin Islands", CurrencyEnum.USD),
    BN("Brunei", CurrencyEnum.BND),
    BG("Bulgaria", CurrencyEnum.BGN),
    BF("Burkina Faso", CurrencyEnum.XAF),
    BI("Burundi", CurrencyEnum.BIF),
    KH("Cambodia", CurrencyEnum.KHR),
    CM("Cameroon", CurrencyEnum.XAF),
    CA("Canada", CurrencyEnum.CAD),
    CV("Cape Verde", CurrencyEnum.CVE),
    KY("Cayman Islands", CurrencyEnum.KYD),
    CF("Central African Republic", CurrencyEnum.XAF),
    TD("Chad", CurrencyEnum.XAF),
    CL("Chile", CurrencyEnum.CLP),
    CN("China", CurrencyEnum.CNY),
    CX("Christmas Island", CurrencyEnum.AUD),
    CC("Cocos Islands", CurrencyEnum.AUD),
    CO("Colombia", CurrencyEnum.COP),
    KM("Comoros", CurrencyEnum.KMF),
    CG("Congo", CurrencyEnum.XAF),
    CK("Cook Islands", CurrencyEnum.NZD),
    CR("Costa Rica", CurrencyEnum.CRC),
    CI("Côte d'Ivoire", CurrencyEnum.XAF),
    HR("Croatia", CurrencyEnum.HRK),
    CU("Cuba", CurrencyEnum.CUP),
    CY("Cyprus", CurrencyEnum.EUR),
    CZ("Czech Republic", CurrencyEnum.CZK),
    DK("Denmark", CurrencyEnum.DKK),
    DJ("Djibouti", CurrencyEnum.DJF),
    DM("Dominica", CurrencyEnum.XCD),
    DO("Dominican Republic", CurrencyEnum.DOP),
    EC("Ecuador", CurrencyEnum.USD),
    EG("Egypt", CurrencyEnum.EGP),
    SV("El Salvador", CurrencyEnum.USD),
    GQ("Equatorial Guinea", CurrencyEnum.XAF),
    ER("Eritrea", CurrencyEnum.ERN),
    EE("Estonia", CurrencyEnum.EEK),
    ET("Ethiopia", CurrencyEnum.ETB),
    FK("Falkland Islands", CurrencyEnum.FKP),
    FO("Faroe Islands", CurrencyEnum.DKK),
    FJ("Fiji", CurrencyEnum.FJD),
    FI("Finland", CurrencyEnum.EUR),
    FR("France", CurrencyEnum.EUR),
    GF("French Guiana", CurrencyEnum.EUR),
    PF("French Polynesia", CurrencyEnum.XPF),
    TF("French Southern Territories", CurrencyEnum.EUR),
    GA("Gabon", CurrencyEnum.XAF),
    GM("Gambia", CurrencyEnum.GMD),
    GE("Georgia", CurrencyEnum.GEL),
    DE("Germany", CurrencyEnum.EUR),
    GH("Ghana", CurrencyEnum.GHS),
    GI("Gibraltar", CurrencyEnum.GIP),
    GR("Greece", CurrencyEnum.EUR),
    GL("Greenland", CurrencyEnum.DKK),
    GD("Grenada", CurrencyEnum.XCD),
    GP("Guadeloupe", CurrencyEnum.EUR),
    GU("Guam", CurrencyEnum.USD),
    GT("Guatemala", CurrencyEnum.GTQ),
    GN("Guinea", CurrencyEnum.GNF),
    GW("Guinea-Bissau", CurrencyEnum.GNF),
    GY("Guyana", CurrencyEnum.GYD),
    HT("Haiti", CurrencyEnum.HTG),
    HM("Heard Island And McDonald Islands", CurrencyEnum.AUD),
    HN("Honduras", CurrencyEnum.HNL),
    HK("Hong Kong", CurrencyEnum.HKD),
    HU("Hungary", CurrencyEnum.HUF),
    IS("Iceland", CurrencyEnum.ISK),
    IN("India", CurrencyEnum.INR),
    ID("Indonesia", CurrencyEnum.IDR),
    IR("Iran", CurrencyEnum.IRR),
    IQ("Iraq", CurrencyEnum.IQD),
    IE("Ireland", CurrencyEnum.EUR),
    IM("Isle Of Man", CurrencyEnum.GBP),
    IL("Israel", CurrencyEnum.ILS),
    IT("Italy", CurrencyEnum.EUR),
    JM("Jamaica", CurrencyEnum.JMD),
    JP("Japan", CurrencyEnum.JPY),
    JE("Jersey", CurrencyEnum.GBP),
    JO("Jordan", CurrencyEnum.JOD),
    KZ("Kazakhstan", CurrencyEnum.KZT),
    KE("Kenya", CurrencyEnum.KES),
    KI("Kiribati", CurrencyEnum.AUD),
    KW("Kuwait", CurrencyEnum.KWD),
    KG("Kyrgyzstan", CurrencyEnum.KGS),
    LA("Laos", CurrencyEnum.LAK),
    LV("Latvia", CurrencyEnum.LVL),
    LB("Lebanon", CurrencyEnum.LBP),
    LS("Lesotho", CurrencyEnum.LSL),
    LR("Liberia", CurrencyEnum.LRD),
    LY("Libya", CurrencyEnum.LYD),
    LI("Liechtenstein", CurrencyEnum.CHF),
    LT("Lithuania", CurrencyEnum.LTL),
    LU("Luxembourg", CurrencyEnum.EUR),
    MO("Macao", CurrencyEnum.MOP),
    MK("Macedonia", CurrencyEnum.MKD),
    MG("Madagascar", CurrencyEnum.MGA),
    MW("Malawi", CurrencyEnum.MWK),
    MY("Malaysia", CurrencyEnum.MYR),
    MV("Maldives", CurrencyEnum.MVR),
    ML("Mali", CurrencyEnum.XAF),
    MT("Malta", CurrencyEnum.EUR),
    MH("Marshall Islands", CurrencyEnum.USD),
    MQ("Martinique", CurrencyEnum.EUR),
    MR("Mauritania", CurrencyEnum.MRO),
    MU("Mauritius", CurrencyEnum.MUR),
    YT("Mayotte", CurrencyEnum.EUR),
    MX("Mexico", CurrencyEnum.MXN),
    FM("Micronesia", CurrencyEnum.USD),
    MD("Moldova", CurrencyEnum.MDL),
    MC("Monaco", CurrencyEnum.EUR),
    MN("Mongolia", CurrencyEnum.MNT),
    ME("Montenegro", CurrencyEnum.EUR),
    MS("Montserrat", CurrencyEnum.XCD),
    MA("Morocco", CurrencyEnum.MAD),
    MZ("Mozambique", CurrencyEnum.MZN),
    MM("Myanmar", CurrencyEnum.MMK),
    NA("Namibia", CurrencyEnum.NAD),
    NR("Nauru", CurrencyEnum.AUD),
    NP("Nepal", CurrencyEnum.NPR),
    NL("Netherlands", CurrencyEnum.EUR),
    AN("Netherlands Antilles", CurrencyEnum.ANG),
    NC("New Caledonia", CurrencyEnum.XPF),
    NZ("New Zealand", CurrencyEnum.NZD),
    NI("Nicaragua", CurrencyEnum.NIO),
    NE("Niger", CurrencyEnum.XOF),
    NG("Nigeria", CurrencyEnum.NGN),
    NU("Niue", CurrencyEnum.NZD),
    NF("Norfolk Island", CurrencyEnum.AUD),
    KP("North Korea", CurrencyEnum.KPW),
    MP("Northern Mariana Islands", CurrencyEnum.USD),
    NO("Norway", CurrencyEnum.NOK),
    OM("Oman", CurrencyEnum.OMR),
    PK("Pakistan", CurrencyEnum.PKR),
    PW("Palau", CurrencyEnum.USD),
    PA("Panama", CurrencyEnum.PAB),
    PG("Papua New Guinea", CurrencyEnum.PGK),
    PY("Paraguay", CurrencyEnum.PYG),
    PE("Peru", CurrencyEnum.PEN),
    PH("Philippines", CurrencyEnum.PHP),
    PN("Pitcairn", CurrencyEnum.NZD),
    PL("Poland", CurrencyEnum.PLN),
    PT("Portugal", CurrencyEnum.EUR),
    PR("Puerto Rico", CurrencyEnum.USD),
    QA("Qatar", CurrencyEnum.QAR),
    RE("Reunion", CurrencyEnum.EUR),
    RO("Romania", CurrencyEnum.RON),
    RU("Russia", CurrencyEnum.RUB),
    RW("Rwanda", CurrencyEnum.RWF),
    SH("Saint Helena", CurrencyEnum.SHP),
    KN("Saint Kitts And Nevis", CurrencyEnum.XCD),
    LC("Saint Lucia", CurrencyEnum.XCD),
    MF("Saint Martin", CurrencyEnum.EUR),
    PM("Saint Pierre And Miquelon", CurrencyEnum.EUR),
    VC("Saint Vincent And The Grenadines", CurrencyEnum.XCD),
    WS("Samoa", CurrencyEnum.WST),
    SM("San Marino", CurrencyEnum.EUR),
    ST("Sao Tome And Principe", CurrencyEnum.STD),
    SA("Saudi Arabia", CurrencyEnum.SAR),
    SN("Senegal", CurrencyEnum.XOF),
    RS("Serbia", CurrencyEnum.RSD),
    CS("Serbia and Montenegro", CurrencyEnum.EUR),
    SC("Seychelles", CurrencyEnum.SCR),
    SL("Sierra Leone", CurrencyEnum.SLL),
    SG("Singapore", CurrencyEnum.SGD),
    SK("Slovakia", CurrencyEnum.EUR),
    SI("Slovenia", CurrencyEnum.EUR),
    SB("Solomon Islands", CurrencyEnum.SBD),
    SO("Somalia", CurrencyEnum.SOS),
    ZA("South Africa", CurrencyEnum.ZAR),
    GS("South Georgia And The South Sandwich Islands", CurrencyEnum.GBP),
    KR("South Korea", CurrencyEnum.KRW),
    ES("Spain", CurrencyEnum.EUR),
    LK("Sri Lanka", CurrencyEnum.LKR),
    SD("Sudan", CurrencyEnum.SDG),
    SR("Suriname", CurrencyEnum.SRD),
    SJ("Svalbard And Jan Mayen", CurrencyEnum.NOK),
    SZ("Swaziland", CurrencyEnum.SZL),
    SE("Sweden", CurrencyEnum.SEK),
    CH("Switzerland", CurrencyEnum.CHF),
    SY("Syria", CurrencyEnum.SYP),
    TW("Taiwan", CurrencyEnum.TWD),
    TJ("Tajikistan", CurrencyEnum.TJS),
    TZ("Tanzania", CurrencyEnum.TZS),
    TH("Thailand", CurrencyEnum.THB),
    CD("Congo/Kinshasa", CurrencyEnum.CDF),
    TG("Togo", CurrencyEnum.XAF),
    TK("Tokelau", CurrencyEnum.NZD),
    TO("Tonga", CurrencyEnum.TOP),
    TT("Trinidad and Tobago", CurrencyEnum.TTD),
    TN("Tunisia", CurrencyEnum.TND),
    TR("Turkey", CurrencyEnum.TRY),
    TM("Turkmenistan", CurrencyEnum.TMM),
    TC("Turks And Caicos Islands", CurrencyEnum.USD),
    TV("Tuvalu", CurrencyEnum.AUD),
    VI("U.S. Virgin Islands", CurrencyEnum.USD),
    UG("Uganda", CurrencyEnum.UGX),
    UA("Ukraine", CurrencyEnum.UAH),
    AE("United Arab Emirates", CurrencyEnum.AED),
    GB("United Kingdom", CurrencyEnum.GBP),
    US("United States", CurrencyEnum.USD),
    UM("United States Minor Outlying Islands", CurrencyEnum.USD),
    UY("Uruguay", CurrencyEnum.UYU),
    UZ("Uzbekistan", CurrencyEnum.UZS),
    VU("Vanuatu", CurrencyEnum.VUV),
    VA("Vatican", CurrencyEnum.EUR),
    VE("Venezuela", CurrencyEnum.VEF),
    VN("Vietnam", CurrencyEnum.VND),
    WF("Wallis And Futuna", CurrencyEnum.XPF),
    EH("Western Sahara", CurrencyEnum.ERN),
    YE("Yemen", CurrencyEnum.YER),
    ZM("Zambia", CurrencyEnum.ZMK),
    ZW("Zimbabwe", CurrencyEnum.USD);

    private String value;
    private CurrencyEnum currency;

    CountryEnum(String value, CurrencyEnum currency) {
        this.value = value;
        this.currency = currency;
    }

    public String toString() {
        return value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public CurrencyEnum getCurrency() {
        return currency;
    }

    public void setCurrency(CurrencyEnum currency) {
        this.currency = currency;
    }

    public static CountryEnum getByDisplayValue(String displayValue) {
        CountryEnum[] a = CountryEnum.values();
        for (int i = 0; i < a.length; i++) {
            CountryEnum e = a[i];
            if (e.toString().equalsIgnoreCase(displayValue)) {
                return e;
            }
        }
        return null;
    }

    public static CurrencyEnum getCurrByCountryCode(String displayValue) {
        CountryEnum[] a = CountryEnum.values();
        for (int i = 0; i < a.length; i++) {
            CountryEnum e = a[i];
            if (e.name().equalsIgnoreCase(displayValue)) {
                return e.currency;
            }
        }
        return null;
    }

}
